version: '3.8'

services:
  db:
    image: mysql:8
    container_name: hrms_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hrms_db
      MYSQL_USER: hrms_user
      MYSQL_PASSWORD: hrms_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
